### ISSUE TITLE
Fire Attachpoints Not Exporting Correctly

### ISSUE THREAD

**Issue by patrochilles** [ptasev/Age-of-Mythology#2]
**Current Behavior**: AoM Model Editor only recognizes one "fire" dummy object when importing a gtlf from blender 2.8 as a brg. The other "fire" dummy objects are deleted.

**Expected Behavior**: AoM Model editor recognizes all objects beginning with "Dummy_fire" and imports them as such, allowing for multiple fire attachpoints in a single model.

**Issue Detailed:** Most building models have several attachpoints all named "fire" (used to connect the fire object to various points in the building as the building takes damage). In Blender (at least using 2.8) it is not possible to have objects with the same name. As a result, the multiple fire dummy objects are named "Dummy_fire.001" "Dummy_fire.002" etc. When importing the exported gtlf file in the Model Editor, all of the fire dummy objects are removed except for one of them (the one simply named "Dummy_fire"). This appears to make it impossible to have multiple fire attachpoints, at least when using Blender. Perhaps a different naming convention would allow all of the dummy fire objects to be recognized by AoM Model Editor?

Note that AoM Model Editor has no problem opening BRG files and exporting them to gtlf with all of the multiple fire objects (each named "Dummy_fire" as expected, which is what the game would recognize). The issue only occurs when importing a gtlf file as a brg in the AoM Model Editor.

**Additional Note**: I gave the code a quick look, and it appears that AoM Model Editor will ignore the capitalization of dummy names. Sure enough, renaming the duplicate "fire" attachpoints to "Dummy_FIRE", "Dummy_FiRe" etc. functions as a workaround allowing multiple fire dummy objects to be recognized by AoM Model Editor when importing gtlf files.

**Comment by ptasev** [comment]
Thanks for the detailed info. I'll have a look when I have some time.

**Comment by ptasev** [comment]
Should be fixed in 1.2.1

**Comment by patrochilles** [comment]
Thanks so much - appreciate all your work developing this great tool (AoM modding has come a long way).
